### ISSUE TITLE
Does not compile/run on Mac OS X.

### ISSUE THREAD

**Issue by ghost** [emanueleforestieri/technicolor_random#1]
Hello there!
I was checking your software that looks really nice.
Although even I've been following your instructions, it does compile with the error "main cannot return void and must return int".
Fair enough, I've changed void to int and the building step was fine.
I run it, no prints on the console anyways.

What am I doing wrong? O.o

My specs:
Macbook Pro with OS X 10.11 El Capitan Beta 6
gcc version 5.2.0
![screen shot 2015-09-08 at 1 14 18 pm](https://cloud.githubusercontent.com/assets/12242171/9733446/8df19438-562b-11e5-8627-70b210e09ac7.png)

**Comment by emanueleforestieri** [comment]
hi!
tries to change void to int and put return 0; at the end of the program before the braces
in this way:
int main()
{
  unsigned char s[11]="XXXXXXXXXX\0",c[17]="0123456789ABCDEF\0";
  srand(time(NULL));
  while(1)
  {
    genera(s,c);
    if(controlla(s,c,0,10,2)&&controlla(s,c,10,16,3)&&tripli(s,c)&&cinque(s,c)<5)
      printf("%s\n",s);  
  }
  return 0;
}

**Comment by ghost** [comment]
Yes, yes. I tried that and the program compiled successfully with just the 2 warnings coloured purple in the previous screenshot.
However still no output on the console, and that's a bit strange.

**Comment by emanueleforestieri** [comment]
probably the output is buffered.
try to put setvbuf(stdout, NULL, _IOLBF, 0); before while loop

**Comment by emanueleforestieri** [comment]
otherwise try to put fflush(stdout); after printf to force the emptying of the buffer i/o and force the output

**Comment by ghost** [comment]
I guess I found the bug.
The _genera()_ function, which generates the string (am I right?), does not return anything to the main().
I simply added a printf into genera() and the words are appearing in the console.

Although all the checks about number of consecutive chars and such are not performed because a simple printf() does not return anything as well, just prints stuff.

**Comment by emanueleforestieri** [comment]
i correct another bug, i have not initialized the variable n in two function
download the new version, try it and let me know :D

**Comment by ghost** [comment]
I still had to change the "void main" vs "int main". But this new version is working perfectly!
No buffered stdout problems whatsoever.
Nice one! problem solved!

**Comment by emanueleforestieri** [comment]
Perfect! :+1:
